name: Publish Updates
on:
  push:
    branches: 
      - 'main'
    paths:
      - 'dependency.lic'
      - 'noop.lic'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    strategy:
      matrix:
        ruby: ['4.0']
    name: Publish Updates
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '20'
      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Release updates to Tillmen's Lich repository
        env:
          AUTHOR: ${{ secrets.repo_author }}
          PASSWORD: ${{ secrets.repo_password }}
          TRAVIS_COMMIT: ${{ github.sha }}
          TRAVIS_COMMIT_RANGE: ${{ github.event.before }}..${{ github.sha }}
        run: bin/repo
